version: '{build}'

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Ubuntu1604
  - Ubuntu1804

platform:
  - x86
  - x64

install:
  - sh: |
      sudo apt-get -qq update
      sudo apt-get -qq install libglfw3-dev pkg-config cmake build-essential ninja-build
  - cmd: |
      vcpkg install glfw3:x86-windows glfw3:x64-windows
      cd c:\tools\vcpkg
      vcpkg integrate install
      cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - sh: |
      cmake -H. -Bbuild -G Ninja
      cmake --build build
  - cmd: |
      cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
      cmake --build build

test: off

cache:
  - c:\tools\vcpkg\installed\ -> .appveyor.yml
